language: go

go:
  - 1.10.x
  - 1.11.x
os:
  - linux
  - osx

install: false
script:
- env GO111MODULE=on go test ./...

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
